development:
  adapter: postgresql
  encoding: utf8
  reconect: false
  database: dataSets
  pool: 5
  username: rails
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconect: false
  database: dataSets
  pool: 5
  username: rails
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconect: false
  database: dataSets
  pool: 5
  username: rails
  password:
  host: localhost
